spring:
  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # Docker Compose
  docker:
    compose:
      lifecycle-management: start_only

# Swagger
swagger:
  server-url: http://localhost:8080
  server-description: Local Server

# PaymentGateway
payment-gateway:
  mid: paymentGatewayMid
  client-key: paymentGatewayClientKey
  secret-key: paymentGatewaySecretKey
  base-url: https://localhost:8089/payment-gateway